#
###################################
# Site wide configuration
####################################
#
title: HBC Tech
tagline: "Engineering the Retail Experience"
tagline-2: "Since 1670"
email: evangelism@hbc.com
description: > # this means to ignore newlines until "baseurl:"
  We power the website and mobile experiences for Saks, 
  Saks Off Fifth, Gilt, Lord & Taylor and The Bay.
baseurl: "" # the subpath of your site, e.g. blog
url: "http://tech.hbc.com" #the base hostname & protocol for your site. 
twitter: hbcdigital
facebook: hbcdigital
github: hbc-tech
linkedin: hbc_digital
instagram: hbcdigital

#google analytics
google_analytics: UA-106560024-1

#
###################################
# Jekyll configuration
####################################
#
timezone: EST
markdown: kramdown
permalink: :year-:month-:day-:title.html
# permalink: pretty
# permalink: /:categories/:year/:month/:day/:title

paginate: 20
paginate_dir: "/"
paginate_path: ":num/"


collections:
  authors:
    output: true
    permalink: "/authors/:path/"
  category:
    permalink: "/category/:path/"
    output: true

defaults:
  - scope:
      type: posts
    values:
      author: HBC Tech
      layout: article
  - scope:
      type: authors
    values:
      layout: author
  - scope:
      type: category
    values:
      layout: category

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

liquid:
  error_mode: warn

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - CNAME
  - docs
  - node_modules
  - gulpfile.js

# Plugin settings
plugins:
  - jekyll-feed
  # - octopress-autoprefixer
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
